### PR TITLE
Added create-react-app example

### PR DESCRIPTION
**Pull request by busypeoples**

### CODE REVIEW

**Comment by steos** [comment]
I get this error when I run `npm run reactcards` in the create-react-app-example directory:

```
ERROR in ./src/App.js
Module not found: Error: Cannot resolve module 'style-loader' in /Users/Stefan.Oestreicher/code/reactcards-example/create-react-app-example/src
 @ ./src/App.js 17:0-20

ERROR in ./src/logo.svg
Module parse failed: /Users/Stefan.Oestreicher/code/reactcards-example/create-react-app-example/src/logo.svg Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
    at Parser.pp$4.raise (/Users/Stefan.Oestreicher/code/reactcards-example/create-react-app-example/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/Stefan.Oestreicher/code/reactcards-example/create-react-app-example/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/Users/Stefan.Oestreicher/code/reactcards-example/create-react-app-example/node_modules/webpack/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/Users/Stefan.Oestreicher/code/reactcards-example/create-react-app-example/node_modules/webpack/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/Users/Stefan.Oestreicher/code/reactcards-example/create-react-app-example/node_modules/webpack/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/Users/Stefan.Oestreicher/code/reactcards-example/create-react-app-example/node_modules/webpack/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/Users/Stefan.Oestreicher/code/reactcards-example/create-react-app-example/node_modules/webpack/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/Users/Stefan.Oestreicher/code/reactcards-example/create-react-app-example/node_modules/webpack/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExpression (/Users/Stefan.Oestreicher/code/reactcards-example/create-react-app-example/node_modules/webpack/node_modules/acorn/dist/acorn.js:1573:21)
    at Parser.pp$1.parseStatement (/Users/Stefan.Oestreicher/code/reactcards-example/create-react-app-example/node_modules/webpack/node_modules/acorn/dist/acorn.js:727:47)
 @ ./src/App.js 13:12-33
```

**Comment by busypeoples** [comment]
We will need to require the updated reactcards

**Comment by steos** [comment]
Ok, I tried it with the latest reactcards but now I get this error when running `npm install`:

```
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/Stefan.Oestreicher/code/reactcards-example/create-react-app-example/node_modules/reactcards/dist/build.js'
```

The reactcards package.json defines a `reactcards-build` in `bin` but the referenced file `./dist/build.js` doesn't exist.

**Comment by busypeoples** [comment]
True. Will remove the reactcards-build. We will introduce the build script later on
https://github.com/steos/reactcards/pull/21 should address the issue.

**Comment by steos** [comment]
Thanks! I've published reactcards 0.4.0 and bumped the dependency in the create-react-app example.

**Pull request merged**
